version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: storage_booking
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/storage_booking
      PORT: 4000
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build: ./frontend
    command: npm run dev
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
    ports:
      - '3001:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
volumes:
  db_data:
